name: Sync to ReadMe
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: readmeio/github-readme-sync@1.0.3
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          readme-api-id: '5ed818eef6a2e50012fb9df7'
          api-file-path: 'src/proxies/helloworld/spec/helloworld.yml'
          readme-api-key: '${{ secrets.README_API_KEY }}'
          readme-api-version: '1.0'
